// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pevateajhqwkvroqjaoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBldmF0ZWFqaHF3a3Zyb3FqYW9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDYzODEsImV4cCI6MjA3MjI4MjM4MX0.B3SifapwufbBrMrPB_KQZaPDxnNKBl0XcJYmCWDgJvg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});